name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
        source-url: https://nuget.pkg.github.com/blaised/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Variables
      run: |
        echo '::set-env name=VERSION_NUMBER::1.0.1-preview02'
        echo '::set-env name=NUGET_URL::https://api.nuget.org/v3/index.json'
        echo '::set-env name=NUGET_API_KEY::${{ secrets.NUGET_API_KEY }}'
        echo '::set-env name=REPO::${{ github.repository }}'
        echo '::set-env name=REPO_OWNER::${{ github.repository_owner }}'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Attributes'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.DataContracts'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Forms.Parameters'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.RulesDirector'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.RulesDirector.AspNetCore'
    - name: Pack and push
      run: ./Release_Pack_Push.ps1
      shell: pwsh